language: node_js
node_js:
  - "10"

deploy:
  provider: npm
  email:
    secure: acQvh77jaknq3Kllt4mfA2bjFCjm3fC0xA1ggKDjjyAukElu+Fcyp2Vurc6uQyS/sE/KEuXihpHl85Vhp/6XlvZMYsL2TVQD+oUJeWEtdw/4WiLB19h/vtzWh9sEf61TjrZPzhbv1HV5PJTHBgZrtQCfT1lWsk1qkW6FzjFB7GXuVCGbmf1Z+haG+oFM50VGXjAEe/jmNGK2gZ3L6xg6aJDBH23DyM/46qsumqk3Uf8Yxal550xgOxoogh5KEGi5nNI4igqTqMUq/aLsY+0znUd4MXik5LvfxiPxK2BRKLP39y4qJe9E6GME7Y+QUFBeQYEKWy5U13CUA3G+xSLhptGwBLCg5h/w9r0XFFxSil0ehrK9NhG0NAibSEFd5tQPXXUOW86MxexfTUGsoQXviNxe1ml54ye1XBu4JsbzJKJxoJWUnh/C/ZM6lpLPDw2btDRR1Ux2wgrdpCLfbF7S4E3ktqvtOc6h7b0xT01iw23ouZCFSrqtHxsfiRSlpO1YIWux4DiY/0SKwXdF8Wn1Kht/bPjkukAj5FCUG21PDRuoX5pm6075syWyvr/na3odHoqlM+KYHIC8Wz+99oxMlMlYcTveFBvLFP4hwfhdh9gKIjGxtsBO+qnTYSlO4LdXkwcLWh9aj7C/0Oui/MS3ya+u46UTLCBOzOG9nzsc/i4=
  api_key:
    secure: ZhIXFrKKChWcKu1rUMSAVKBtpOj5OZxx/FFZHI5leNQXP26pQi32P9cdDzxdqD5HBJbFCb4vu3+vv1tTpCJZbZNbwB2rpe81TRTbzi1cfPdEL1NYcdxF0E1IphTsSDnA7rmG+2IBIYEzZacYHwshuFByYsqdcZ4SgExsuA2mu13MEC4USnf40SMRB9aZKIyy5qX5IKyXawvH6uh69dM1s+Em3MkmmlUZ2a1YpQk37+MoDyqL8HO08hq2pjV6YdJ2kAISY6FnOUwSYzl3sd/dELf2yzKZ2SYw8JrmyXmrPQBTtGAzJXXMQrUmz6lKT32imKWzbT3mmQX1n93LPNqN3wPJGBVOXzrLF1yuSLrqNQHVENjKJhJ4ktako0MY4cJ8lrC1A6rIcgLv/p0k57WEvf+3aVFJljod/y0YbzvJ9ha2bko8pGgZ1Y72v6kM0M1l6k/1XQSg7o+gPlCWpUBYo3ndsiAlTD8h4nG3qQNQhLvahUQEZOlLNs44XZZKhu0Mr6M3ViHNh7HKWwKU9inkNFVbMuyvZ96Yxdu2tj9weMo8KEoar+RgJq/fLg86KqxiqbfWJrSlyy/1T2EuOP929IuLcHhgx6JsWPq3/qEE4ZzNUQ3cgf2Clu9k+B6v6iBQzJGMhCo1Hr/ron1cjP13x1/shGruZEUU3eZT8mq+59A=


